# Generated by Django 3.1.5 on 2021-01-14 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('isbn', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['isbn', 'title'],
            },
        ),
    ]
